"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import AppShell from "@/app/_components/AppShell";
import MeetingTabs from "@/app/_components/MeetingTabs";
import { Badge, Card, Field, Message, PageTitle, formatDate } from "@/app/_components/ui";
import { ApiError, apiFetch, jsonBody } from "@/app/_lib/api";
import type { ScheduleCandidate, SchedulePoll } from "@/app/_lib/types";

export default function ScheduleManagePage() {
  const { meetingId } = useParams<{ meetingId: string }>(); const [poll, setPoll] = useState<SchedulePoll | null>(null); const [missing, setMissing] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [editing, setEditing] = useState<number | null>(null); const [editDate, setEditDate] = useState("");
  const load = useCallback(() => apiFetch<SchedulePoll>(`/api/meetings/${meetingId}/schedule-poll`).then((data) => { setPoll(data); setMissing(false); }).catch((e) => { if (e instanceof ApiError && e.status === 404) setMissing(true); else setError(e.message); }), [meetingId]);
  useEffect(() => { void load(); }, [load]);
  async function createPoll(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await apiFetch(`/api/meetings/${meetingId}/schedule-poll`, { method: "POST", body: jsonBody({ deadline: form.get("deadline") }) }); load(); } catch (e) { setError(e instanceof Error ? e.message : "투표를 만들지 못했습니다."); } }
  async function updateDeadline(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { const data = await apiFetch<{ deadline: string }>(`/api/meetings/${meetingId}/schedule-poll`, { method: "PATCH", body: jsonBody({ deadline: form.get("deadline") }) }); setPoll((current) => current ? { ...current, deadline: data.deadline } : current); setMessage("마감 시간을 변경했습니다."); } catch (e) { setError(e instanceof Error ? e.message : "변경하지 못했습니다."); } }
  async function addCandidate(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { const candidate = await apiFetch<ScheduleCandidate>(`/api/meetings/${meetingId}/schedule-poll/candidates`, { method: "POST", body: jsonBody({ candidateDate: form.get("candidateDate") }) }); setPoll((current) => current ? { ...current, candidates: [...current.candidates, candidate] } : current); event.currentTarget.reset(); } catch (e) { setError(e instanceof Error ? e.message : "후보를 추가하지 못했습니다."); } }
  async function updateCandidate(id: number) { try { const candidate = await apiFetch<ScheduleCandidate>(`/api/meetings/${meetingId}/schedule-poll/candidates/${id}`, { method: "PATCH", body: jsonBody({ candidateDate: editDate }) }); setPoll((current) => current ? { ...current, candidates: current.candidates.map((item) => item.id === id ? candidate : item) } : current); setEditing(null); } catch (e) { setError(e instanceof Error ? e.message : "수정하지 못했습니다. 이미 응답이 있는 후보일 수 있습니다."); } }
  async function removeCandidate(id: number) { try { await apiFetch<void>(`/api/meetings/${meetingId}/schedule-poll/candidates/${id}`, { method: "DELETE" }); setPoll((current) => current ? { ...current, candidates: current.candidates.filter((item) => item.id !== id) } : current); } catch (e) { setError(e instanceof Error ? e.message : "삭제하지 못했습니다. 이미 응답이 있는 후보일 수 있습니다."); } }
  return <AppShell><PageTitle eyebrow="Host tools" title="일정 후보 관리" description="마감일을 설정하고 최대 10개의 날짜 후보를 관리하세요." action={<Link className="button button-secondary" href={`/meetings/${meetingId}/schedule/results`}>결과 보기</Link>} /><MeetingTabs meetingId={meetingId} active="schedule" />{message && <Message tone="success">{message}</Message>}{error && <Message tone="error">{error}</Message>}{missing && <Card><h2>일정 투표 만들기</h2><form className="row" onSubmit={createPoll}><input className="input" type="datetime-local" name="deadline" required /><button className="button button-primary">투표 만들기</button></form></Card>}{poll && <div className="stack"><Card><div className="row between"><div><Badge tone={poll.status === "OPEN" ? "green" : "gray"}>{poll.status}</Badge><h2>마감 {formatDate(poll.deadline)}</h2></div><span className="muted">후보 {poll.candidates.length}/10</span></div><form className="row" onSubmit={updateDeadline}><Field label="마감 시간 변경"><input className="input" name="deadline" type="datetime-local" required /></Field><button className="button button-secondary">변경</button></form></Card><Card><h2>새 날짜 후보</h2><form className="row" onSubmit={addCandidate}><input className="input" name="candidateDate" type="date" required /><button className="button button-primary" disabled={poll.status === "CLOSED" || poll.candidates.length >= 10}>후보 추가</button></form><div className="divider" /><div className="list">{poll.candidates.map((candidate) => <div className="list-item" key={candidate.id}>{editing === candidate.id ? <input className="input" type="date" value={editDate} onChange={(e) => setEditDate(e.target.value)} /> : <div><strong>{candidate.candidateDate}</strong><p>후보 #{candidate.id}</p></div>}<div className="row">{editing === candidate.id ? <><button className="button button-primary button-small" onClick={() => updateCandidate(candidate.id)}>저장</button><button className="button button-ghost button-small" onClick={() => setEditing(null)}>취소</button></> : <button className="button button-ghost button-small" onClick={() => { setEditing(candidate.id); setEditDate(candidate.candidateDate); }}>수정</button>}<button className="button button-danger button-small" onClick={() => removeCandidate(candidate.id)}>삭제</button></div></div>)}</div><Message>응답이 있는 후보는 서버 정책에 따라 수정하거나 삭제할 수 없습니다.</Message></Card></div>}</AppShell>;
}
