"use client";
import { useParams, useRouter } from "next/navigation";
import { useEffect, useState, type FormEvent } from "react";
import AppShell from "@/app/_components/AppShell";
import MeetingTabs from "@/app/_components/MeetingTabs";
import { Card, Field, Message, PageTitle } from "@/app/_components/ui";
import { apiFetch, getCurrentUserId, jsonBody } from "@/app/_lib/api";
import type { MeetingMember } from "@/app/_lib/types";

type SplitMode = "EQUAL" | "EXACT";
export default function ExpenseCreatePage() {
  const { meetingId } = useParams<{ meetingId: string }>(); const router = useRouter(); const [members, setMembers] = useState<MeetingMember[]>([]); const [selected, setSelected] = useState<number[]>([]); const [amounts, setAmounts] = useState<Record<number, string>>({}); const [mode, setMode] = useState<SplitMode>("EQUAL"); const [advanced, setAdvanced] = useState(false); const [error, setError] = useState("");
  const me = members.find((member) => member.userId === getCurrentUserId());
  useEffect(() => { apiFetch<MeetingMember[]>(`/api/meetings/${meetingId}/members`).then((items) => { setMembers(items); setSelected(items.map((item) => item.id)); }).catch((e) => setError(e.message)); }, [meetingId]);
  function toggle(id: number) { setSelected((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id]); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const participants = selected.map((memberId) => ({ memberId, amount: mode === "EXACT" ? Number(amounts[memberId] || 0) : null })); try { await apiFetch(`/api/meetings/${meetingId}/expenses`, { method: "POST", body: jsonBody({ title: form.get("title"), amount: Number(form.get("amount")), memo: form.get("memo"), splitMode: mode, roundingUnit: advanced && form.get("roundingUnit") ? Number(form.get("roundingUnit")) : null, remainderMemberId: advanced && form.get("remainderMemberId") ? Number(form.get("remainderMemberId")) : null, participants, randomRemainder: advanced ? form.get("randomRemainder") === "on" : false }) }); router.push(`/meetings/${meetingId}/settlement`); } catch (e) { setError(e instanceof Error ? e.message : "지출을 등록하지 못했습니다."); } }
  return <AppShell><PageTitle eyebrow="New expense" title="지출 등록" description="결제한 금액과 실제 부담할 참여자를 선택하세요." /><MeetingTabs meetingId={meetingId} active="settlement" />{error && <Message tone="error">{error}</Message>}<Card><form className="stack" onSubmit={submit}><div className="grid grid-2"><Field label="지출 제목"><input className="input" name="title" required /></Field><Field label="금액"><input className="input" name="amount" type="number" min="1" step="1" required /></Field></div><Field label="메모 (선택)"><textarea className="textarea" name="memo" /></Field><Field label="결제자"><input className="input" disabled value={me ? `${me.nickname} (나)` : "로그인한 사용자"} /></Field><Field label="분배 방식"><div className="pill-options"><button type="button" className={`choice ${mode === "EQUAL" ? "selected" : ""}`} onClick={() => setMode("EQUAL")}>균등 분배</button><button type="button" className={`choice ${mode === "EXACT" ? "selected" : ""}`} onClick={() => setMode("EXACT")}>직접 입력</button></div></Field><div><strong>부담 참여자</strong>{members.map((member) => <div className="checkbox-row" key={member.id}><input type="checkbox" checked={selected.includes(member.id)} onChange={() => toggle(member.id)} /><span>{member.nickname}</span>{mode === "EXACT" && selected.includes(member.id) && <input className="input" type="number" min="0" step="1" placeholder="부담 금액" value={amounts[member.id] || ""} onChange={(e) => setAmounts((all) => ({ ...all, [member.id]: e.target.value }))} />}</div>)}</div><button type="button" className="button button-ghost" onClick={() => setAdvanced(!advanced)}>{advanced ? "추가 옵션 닫기" : "반올림·나머지 추가 옵션"}</button>{advanced && <Card><div className="grid grid-2"><Field label="반올림 단위"><input className="input" name="roundingUnit" type="number" min="1" /></Field><Field label="나머지 부담자"><select className="select" name="remainderMemberId"><option value="">선택 안 함</option>{members.map((member) => <option key={member.id} value={member.id}>{member.nickname}</option>)}</select></Field></div><label className="checkbox-row"><input type="checkbox" name="randomRemainder" />나머지 부담자를 무작위로 선택</label></Card>}<div className="form-actions"><button type="button" className="button button-ghost" onClick={() => router.back()}>취소</button><button className="button button-primary" disabled={selected.length === 0}>지출 등록 완료</button></div></form></Card></AppShell>;
}
