spring:
  application:
    name: backend


  config:
    import: optional:file:.env[.properties]

  # DB 연결 정보 (.env 값 주입)
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQLUSER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true